easy_admin:
    list:
        max_results: 100

    entities:
        ShoppingList:
            class: App\Entity\ShoppingList
            label: List

            disabled_actions: ['delete', 'edit', 'new']

            list:
                title: Lists
                actions:
                    - label: Show
                      name: shopping_list_items
                      type: route

        Store:
            class: App\Entity\Store
            label: Store

            disabled_actions: ['delete']

            list:
                title: Stores
                sort: ['name', 'ASC']
