services:
  node:
    image: node:20
    profiles:
      - dev
    working_dir: /app
    volumes:
      - .:/app:delegated

  playwright:
    # https://playwright.dev/docs/docker
    # This Playwright version should match the one in `package.json`.
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    profiles:
      - test
    networks:
      - app
    depends_on:
      - nginx
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app
