on: pull_request
name: Review
jobs:
  # changelog:
  #   runs-on: ubuntu-latest
  #   name: Changelog should be updated
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 2

  #     - name: Git fetch
  #       run: git fetch

  #     - name: Check that changelog has been updated.
  #       run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  translations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2' ]
    name: Check translations are up to date (${{ matrix.php}})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update translations
        run: |
          docker compose run --rm phpfpm composer install --no-scripts
          docker compose run --rm phpfpm composer update-translations
      - name: Check for changes in translation files
        run: |
          git diff --diff-filter=ACMRT --exit-code translations

  coding-standards-markdown:
    name: Coding Standards Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: |
          yarn install
          yarn coding-standards-check
