on: pull_request
name: Review
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git fetch
        run: git fetch
      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  coding-standards-markdown:
    name: Markdown coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-go-task-task-taskfile
      - uses: pnorton5432/setup-task@v1
      - name: Check coding standards
        run: TASK_NO_APPLY=true task dev:coding-standards:markdown:check

  coding-standards-javascript:
    name: JavaScript coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnorton5432/setup-task@v1
      - name: Check coding standards
        run: TASK_NO_APPLY=true task dev:coding-standards:javascript:check

  coding-standards-scss:
    name: SCSS coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnorton5432/setup-task@v1
      - name: Check coding standards
        run: TASK_NO_APPLY=true  task dev:coding-standards:scss:check

  coding-standards-php:
    name: PHP coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnorton5432/setup-task@v1
      - name: Check coding standards
        run: TASK_NO_APPLY=true task dev:coding-standards:php:check

  coding-standards-twig:
    name: Twig coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnorton5432/setup-task@v1
      - name: Check coding standards
        run: TASK_NO_APPLY=true task dev:coding-standards:twig:check

  translations:
    runs-on: ubuntu-latest
    name: Check translations are up to date
    steps:
      - uses: actions/checkout@v4
      - uses: pnorton5432/setup-task@v1
      - name: Update translations
        run: task dev:translations:update
      - name: Check for changes in translation files
        run: git diff --diff-filter=ACMRT --exit-code

  # code-analysis-php:
  #   name: PHP code analysis
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pnorton5432/setup-task@v1
  #     - name: Analyze code
  #       run: task dev:code-analysis:php
